[theme.dev]
refresh = -1
log = true
debug = false

[theme.options]
stealth_mode = false
fg_image = ""
bg_color = "Black"
bg_image = "320x240e-t-g.png"
bg_anim_image = ""
font_sizes = [ 10, 8, 10, 55, 25, 9,]
font = "DejaVuSansMono"
font_bold = "DejaVuSansMono-Bold.ttf"
status_font = "DejaVuSansMono"
font_awesome = "font-awesome-solid.otf"
label_spacing = 9
size_offset = 5
cursor = "❤"
friend_bars = ">"
friend_no_bars = "│"
base_text_color = [ "lime",]
main_text_color = []
color_mode = [ "P", "P",]
boot_animation = true
boot_max_loops = 1
boot_total_duration = 2

[theme.menu.options]
motion_text = true
motion_text_speed = 20
position = [ "center", "bottom",]
width = "100%"
height = 127
button_height = 20
text_font_size = "Medium"
timeout = 0
border_color = "black"
highlight_color = "#ff9800"
highlight_text_color = "black"
button_bg_color = "black"
button_text_color = "white"
button_font_size = "Medium"
bg_color = "black"

[theme.widget.face]
position = [ 22, 19,]
text_font_size = "Huge"
color = [ "lime",]
icon = true
icon_color = true
mask = true
refine = 150
image_type = "png"
f_awesome = false
f_awesome_size = 40
zoom = 0.92
z_axis = 102

[theme.widget.name]
position = [ 55, 3,]
text_font_size = "Bold"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.channel]
position = [ 278, 96,]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.aps]
position = [ 216, 96,]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 0
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = true
f_awesome_size = 20
z_axis = 0

[theme.widget.uptime]
position = [ 134, 3,]
label = "UP"
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
color = [ "#6b8c3a",]
icon = false
f_awesome = false
f_awesome_size = 40

[theme.widget.line1]
position = [ 0, 0, 320, 0,]
color = [ "lime",]
z_axis = 0

[theme.widget.line2]
position = [ 0, 0, 320, 0,]
color = [ "lime",]
z_axis = 0

[theme.widget.friend_face]
position = [ 94, 175,]
text_font_size = "Medium"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.friend_name]
position = [ 24, 175,]
text_font_size = "Medium"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.shakes]
position = [ 34, 193,]
label = "PWND"
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.mode]
position = [ 22, 3,]
text_font_size = "Bold"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.status]
position = [ 24, 124,]
text_font_size = "Bold"
color = [ "#97cc2d",]
wrap = true
max = 20
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.clock]
position = [ 250, 193,]
text_font_size = "Medium"
color = [ "lime",]
wrap = true
max = 20
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.bluetooth]
position = [ 276, 170,]
label = "BT"
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = true
f_awesome_size = 40
z_axis = 0

[theme.widget.memtemp_cpu]
position = [ 219, 23,]
color = [ "lime",]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.memtemp_mem]
position = [ 273, 23,]
color = [ "lime",]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.memtemp_temp]
position = [ 218, 61,]
color = [ "lime",]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.memtemp_freq]
position = [ 271, 61,]
color = [ "lime",]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.bat]
position = [ 270, 61,]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = true
f_awesome_size = 40
z_axis = 0

[theme.widget.deauth_count]
position = [ 224, 134,]
color = [ "lime",]
label = "D"
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.assoc_count]
position = [ 277, 134,]
label = "A"
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = true
f_awesome_size = 40
z_axis = 0

[theme.widget.Lv]
position = [ 24, 112,]
text_font_size = "Medium"
color = [ "lime",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.Str]
position = [ 58, 112,]
text_font_size = "Medium"
color = [ "lime",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.Exp]
position = [ 115, 112,]
text_font_size = "Bold"
color = [ "lime",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.connection_status]
position = [ 35, 208,]
text_font_size = "Medium"
color = [ "lime",]
f_awesome = true
f_awesome_size = 40
z_axis = 0

[theme.widget.ip1]
position = [ 189, 208,]
text_font_size = "Medium"
color = [ "red",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.show_pwd]
position = [ 64, 204,]
text_font_size = "Medium"
color = [ "red",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.wardriver_icon]
position = [ 110, 20,]
text_font_size = "Medium"
color = [ "lime",]
icon = true
icon_color = false
mask = true
refine = 150
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.wardriver]
position = [ 110, 20,]
text_font_size = "Medium"
color = [ "lime",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.fix]
position = [ 121, 35,]
text_font_size = "Medium"
color = [ "#633a8c",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.lat]
position = [ 121, 50,]
text_font_size = "Medium"
color = [ "#613d85",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.lon]
position = [ 121, 65,]
text_font_size = "Medium"
color = [ "#5a3d78",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.alt]
position = [ 121, 80,]
text_font_size = "Medium"
color = [ "#684c87",]
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.spd]
position = [ 121, 95,]
text_font_size = "Medium"
color = [ "#8060a3",]
f_awesome = false
f_awesome_size = 40
z_axis = 0
